"use client";
import { useEffect,useState } from "react";

type ImageItem={id:string|number;url:string;alt?:string;display_order?:number};
export function ProjectGallery({projectTitle,cover,images,accent="#0B3A64"}:{projectTitle:string;cover?:string|null;images:ImageItem[];accent?:string}){
 const all=[cover?{id:"cover",url:cover,alt:projectTitle}:null,...images].filter(Boolean) as ImageItem[];const [active,setActive]=useState<number|null>(null);
 useEffect(()=>{if(active===null)return;const key=(e:KeyboardEvent)=>{if(e.key==="Escape")setActive(null);if(e.key==="ArrowRight")setActive(i=>i===null?0:(i+1)%all.length);if(e.key==="ArrowLeft")setActive(i=>i===null?0:(i-1+all.length)%all.length)};window.addEventListener("keydown",key);return()=>window.removeEventListener("keydown",key)},[active,all.length]);
 if(!all.length)return <section className="mx-auto max-w-7xl px-5 pb-24 text-stone-500">Nenhuma imagem cadastrada para este projeto.</section>;
 return <><section className="mx-auto max-w-[1400px] px-5 pb-24 sm:px-8 lg:px-12"><div className="grid auto-rows-[150px] grid-cols-2 gap-3 sm:auto-rows-[190px] sm:gap-4 lg:grid-cols-12">{all.map((image,index)=><button key={image.id} type="button" onClick={()=>setActive(index)} className={`${index===0?"col-span-2 row-span-3 lg:col-span-8 lg:row-span-4":"col-span-1 row-span-2 lg:col-span-4 lg:row-span-2"} group relative overflow-hidden bg-stone-200 text-left focus:outline-none focus-visible:ring-2 focus-visible:ring-offset-4`} style={{outlineColor:accent}}><img src={image.url} alt={image.alt||projectTitle} className="h-full w-full object-cover transition duration-700 group-hover:scale-105"/><span className="absolute inset-0 bg-gradient-to-t from-black/55 via-transparent to-transparent opacity-0 transition group-hover:opacity-100"/><span className="absolute bottom-4 left-4 font-mono text-[10px] uppercase tracking-[.2em] text-white opacity-0 transition group-hover:opacity-100">Abrir · {String(index+1).padStart(2,"0")}</span></button>)}</div></section>{active!==null&&<div className="fixed inset-0 z-[100] grid place-items-center bg-black/92 p-4 backdrop-blur-md" role="dialog" aria-modal="true" onClick={()=>setActive(null)}><button type="button" onClick={e=>{e.stopPropagation();setActive(null)}} className="absolute right-5 top-5 z-10 h-11 w-11 border border-white/20 bg-black/40 text-xl text-white">×</button><button type="button" aria-label="Imagem anterior" onClick={e=>{e.stopPropagation();setActive(i=>(i===null?0:(i-1+all.length)%all.length))}} className="absolute left-3 z-10 hidden h-12 w-12 border border-white/20 bg-black/40 text-2xl text-white sm:block">‹</button><figure onClick={e=>e.stopPropagation()} className="relative max-h-[92vh] max-w-[94vw] overflow-hidden border bg-black" style={{borderColor:accent,boxShadow:`0 0 0 1px ${accent}66,0 25px 90px rgba(0,0,0,.65)`}}><img src={all[active].url} alt={all[active].alt||projectTitle} className="max-h-[82vh] max-w-[90vw] object-contain"/><figcaption className="flex items-center justify-between bg-black/85 px-4 py-3 text-sm text-white"><span>{projectTitle}</span><span className="font-mono text-white/55">{active+1} / {all.length}</span></figcaption></figure><button type="button" aria-label="Próxima imagem" onClick={e=>{e.stopPropagation();setActive(i=>(i===null?0:(i+1)%all.length))}} className="absolute right-3 z-10 hidden h-12 w-12 border border-white/20 bg-black/40 text-2xl text-white sm:block">›</button></div>}</>;
}
