"use client";
import Link from "next/link";
import { useEffect, useState, type ReactNode } from "react";
import { createClient } from "@/lib/supabase/client";
import { DEFAULT_HOMEPAGE, type GalleryImage, type HomepageContent } from "@/lib/cms-defaults";

export default function AdminConteudoV2(){
 const [content,setContent]=useState<HomepageContent>(DEFAULT_HOMEPAGE),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[uploading,setUploading]=useState<string|null>(null),[message,setMessage]=useState("");
 useEffect(()=>{(async()=>{const s=createClient();const {data,error}=await s.from("site_content").select("value").eq("key","homepage").maybeSingle();if(error)setMessage(error.message);if(data?.value&&typeof data.value==="object"){const v=data.value as Partial<HomepageContent>;setContent({...DEFAULT_HOMEPAGE,...v,hero:{...DEFAULT_HOMEPAGE.hero,...(v.hero??{})},areas:{...DEFAULT_HOMEPAGE.areas,...(v.areas??{})},gallery:{...DEFAULT_HOMEPAGE.gallery,...(v.gallery??{}),images:Array.isArray(v.gallery?.images)?v.gallery.images:[]},method:{...DEFAULT_HOMEPAGE.method,...(v.method??{})},finalCta:{...DEFAULT_HOMEPAGE.finalCta,...(v.finalCta??{})}})}setLoading(false)})()},[]);
 async function save(next=content){setSaving(true);setMessage("");const s=createClient();const {error}=await s.from("site_content").upsert({key:"homepage",value:next,updated_at:new Date().toISOString()},{onConflict:"key"});setMessage(error?`Não foi possível salvar: ${error.message}`:"Conteúdo salvo e publicado.");if(!error)setContent(next);setSaving(false)}
 async function upload(section:"hero"|"gallery",file:File,index?:number){setUploading(`${section}-${index??"new"}`);setMessage("");const s=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${section}/${crypto.randomUUID()}.${ext}`;const up=await s.storage.from("site-media").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMessage(`Upload: ${up.error.message}`);setUploading(null);return}const {data}=s.storage.from("site-media").getPublicUrl(path);const next=section==="hero"?{...content,hero:{...content.hero,images:[...content.hero.images,{image:data.publicUrl,alt:"Obra Nascimento Reformas"}]}}:{...content,gallery:{...content.gallery,images:[...content.gallery.images,{image:data.publicUrl,alt:"Obra Nascimento Reformas",label:""}]}};await save(next);setUploading(null)}
 async function replace(section:"hero"|"gallery",index:number,file:File){setUploading(`${section}-${index}`);setMessage("");const s=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`${section}/${crypto.randomUUID()}.${ext}`;const up=await s.storage.from("site-media").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMessage(`Upload: ${up.error.message}`);setUploading(null);return}const {data}=s.storage.from("site-media").getPublicUrl(path);const next=section==="hero"?{...content,hero:{...content.hero,images:content.hero.images.map((item,i)=>i===index?{...item,image:data.publicUrl}:item)}}:{...content,gallery:{...content.gallery,images:content.gallery.images.map((item,i)=>i===index?{...item,image:data.publicUrl}:item)}};await save(next);setUploading(null)}
 async function remove(section:"hero"|"gallery",index:number){const next=section==="hero"?{...content,hero:{...content.hero,images:content.hero.images.filter((_,i)=>i!==index)}}:{...content,gallery:{...content.gallery,images:content.gallery.images.filter((_,i)=>i!==index)}};await save(next)}
 function setGalleryImage(index:number,changes:Partial<GalleryImage>){setContent(c=>({...c,gallery:{...c.gallery,images:c.gallery.images.map((item,i)=>i===index?{...item,...changes}:item)}}))}
 if(loading)return <div className="min-h-screen bg-stone-100 p-8">Carregando conteúdo…</div>;
 return <div className="min-h-screen bg-stone-100"><header className="sticky top-0 z-20 border-b border-stone-200 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><Link href="/admin/dashboard" className="text-xs uppercase tracking-widest text-stone-500">← Dashboard</Link><h1 className="mt-1 text-xl font-semibold text-navy-950">Conteúdo do site</h1></div><button onClick={()=>save()} disabled={saving} className="rounded-lg bg-navy-900 px-5 py-2.5 text-sm font-semibold text-white">{saving?"Salvando…":"Salvar alterações"}</button></div></header><main className="mx-auto max-w-7xl space-y-8 px-5 py-8">{message&&<div className="border border-stone-200 bg-white px-4 py-3 text-sm text-navy-900">{message}</div>}
 <Editor title="Hero · primeira impressão" subtitle="Textos, intervalo, overlay, grade e imagens."><div className="grid gap-5 lg:grid-cols-2"><Input label="Eyebrow" value={content.hero.eyebrow} onChange={v=>setContent(c=>({...c,hero:{...c.hero,eyebrow:v}}))}/><Input label="Título" value={content.hero.title} onChange={v=>setContent(c=>({...c,hero:{...c.hero,title:v}}))}/><Input label="Destaque" value={content.hero.highlight} onChange={v=>setContent(c=>({...c,hero:{...c.hero,highlight:v}}))}/><Input label="Intervalo (ms)" type="number" value={String(content.hero.heroInterval)} onChange={v=>setContent(c=>({...c,hero:{...c.hero,heroInterval:Math.max(2500,Number(v)||6500)}}))}/><TextArea label="Descrição" value={content.hero.description} onChange={v=>setContent(c=>({...c,hero:{...c.hero,description:v}}))}/><TextArea label="Texto do card" value={content.hero.panelText} onChange={v=>setContent(c=>({...c,hero:{...c.hero,panelText:v}}))}/></div><label className="mt-5 flex items-center gap-2 border-t border-stone-100 pt-5 text-sm"><input type="checkbox" checked={content.hero.showGrid} onChange={e=>setContent(c=>({...c,hero:{...c.hero,showGrid:e.target.checked}}))}/> Mostrar grade arquitetônica</label><ImageManager title="Imagens da hero" images={content.hero.images} uploading={uploading} onUpload={f=>upload("hero",f)} onReplace={(i,f)=>replace("hero",i,f)} onRemove={i=>remove("hero",i)}/></Editor>
 <Editor title="Áreas de atuação" subtitle="Os cards têm uma única fonte de verdade. Edite os cards em Categorias para não haver dois cadastros concorrentes."><div className="grid gap-5 lg:grid-cols-2"><Input label="Eyebrow" value={content.areas.eyebrow} onChange={v=>setContent(c=>({...c,areas:{...c.areas,eyebrow:v}}))}/><Input label="Título" value={content.areas.title} onChange={v=>setContent(c=>({...c,areas:{...c.areas,title:v}}))}/><Input label="Destaque" value={content.areas.highlight} onChange={v=>setContent(c=>({...c,areas:{...c.areas,highlight:v}}))}/><TextArea label="Descrição" value={content.areas.description} onChange={v=>setContent(c=>({...c,areas:{...c.areas,description:v}}))}/></div><div className="mt-6 flex items-center justify-between border-t border-stone-100 pt-5"><p className="text-sm text-stone-500">Os {content.areas.categories.length} cards atuais são controlados no menu Categorias.</p><Link href="/admin/categorias" className="rounded-lg bg-navy-900 px-4 py-2.5 text-sm font-semibold text-white">Editar cards</Link></div></Editor>
 <Editor title="Galeria horizontal" subtitle="Fica entre Áreas de atuação e Nosso método. As imagens não são clicáveis, rolam automaticamente para a esquerda e podem ser substituídas aqui."><div className="grid gap-5 lg:grid-cols-2"><Input label="Eyebrow" value={content.gallery.eyebrow} onChange={v=>setContent(c=>({...c,gallery:{...c.gallery,eyebrow:v}}))}/><Input label="Título" value={content.gallery.title} onChange={v=>setContent(c=>({...c,gallery:{...c.gallery,title:v}}))}/><Input label="Intervalo automático (ms)" type="number" value={String(content.gallery.interval)} onChange={v=>setContent(c=>({...c,gallery:{...c.gallery,interval:Math.max(3500,Number(v)||6200)}}))}/></div><ImageManager title="Imagens da galeria" images={content.gallery.images} uploading={uploading} onUpload={f=>upload("gallery",f)} onReplace={(i,f)=>replace("gallery",i,f)} onRemove={i=>remove("gallery",i)} renderMeta={(image,index)=><div className="grid gap-2 p-3"><Input label="Legenda" value={image.label||""} onChange={v=>setGalleryImage(index,{label:v})}/><Input label="Texto alternativo" value={image.alt||""} onChange={v=>setGalleryImage(index,{alt:v})}/></div>}/><p className="mt-4 text-xs text-stone-500">Legendas e textos alternativos ficam no estado local até você clicar em Salvar alterações.</p></Editor>
 <Editor title="Nosso método" subtitle="Seção de processo e confiança."><div className="grid gap-5 lg:grid-cols-2"><Input label="Eyebrow" value={content.method.eyebrow} onChange={v=>setContent(c=>({...c,method:{...c.method,eyebrow:v}}))}/><Input label="Título" value={content.method.title} onChange={v=>setContent(c=>({...c,method:{...c.method,title:v}}))}/><Input label="Destaque" value={content.method.highlight} onChange={v=>setContent(c=>({...c,method:{...c.method,highlight:v}}))}/><TextArea label="Descrição" value={content.method.description} onChange={v=>setContent(c=>({...c,method:{...c.method,description:v}}))}/></div></Editor>
 <Editor title="CTA final" subtitle="Última chamada para orçamento."><div className="grid gap-5 lg:grid-cols-3"><Input label="Título" value={content.finalCta.title} onChange={v=>setContent(c=>({...c,finalCta:{...c.finalCta,title:v}}))}/><Input label="Botão" value={content.finalCta.button} onChange={v=>setContent(c=>({...c,finalCta:{...c.finalCta,button:v}}))}/><TextArea label="Descrição" value={content.finalCta.description} onChange={v=>setContent(c=>({...c,finalCta:{...c.finalCta,description:v}}))}/></div></Editor>
 <button onClick={()=>save()} disabled={saving} className="rounded-lg bg-navy-900 px-6 py-3 text-sm font-semibold text-white">{saving?"Salvando…":"Salvar e publicar tudo"}</button></main></div>
}
function Editor({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <section className="border border-stone-200 bg-white p-6 shadow-sm sm:p-8"><div className="mb-7 border-b border-stone-100 pb-5"><h2 className="text-xl font-semibold text-navy-950">{title}</h2><p className="mt-1 text-sm text-stone-500">{subtitle}</p></div>{children}</section>}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-stone-500">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-lg border border-stone-300 px-3 text-sm"/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-stone-500">{label}</span><textarea rows={4} value={value} onChange={e=>onChange(e.target.value)} className="w-full rounded-lg border border-stone-300 p-3 text-sm"/></label>}
function ImageManager({title,images,uploading,onUpload,onReplace,onRemove,renderMeta}:{title:string;images:{image:string;alt?:string;label?:string}[];uploading:string|null;onUpload:(file:File)=>void;onReplace:(index:number,file:File)=>void;onRemove:(index:number)=>void;renderMeta?:(image:GalleryImage,index:number)=>ReactNode}){return <div className="mt-7 border-t border-stone-100 pt-6"><div className="flex items-center justify-between gap-4"><div><p className="text-sm font-semibold text-navy-900">{title}</p><p className="text-xs text-stone-500">Você pode inserir novas imagens ou trocar qualquer imagem existente.</p></div><label className="cursor-pointer rounded-lg bg-navy-900 px-4 py-2.5 text-sm font-semibold text-white">{uploading?.includes("new")?"Enviando…":"Adicionar imagem"}<input type="file" accept="image/*" className="hidden" disabled={!!uploading} onChange={e=>{const file=e.target.files?.[0];if(file)onUpload(file);e.currentTarget.value=""}}/></label></div><div className="mt-5 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{images.map((image,index)=><article key={`${image.image}-${index}`} className="overflow-hidden border border-stone-200 bg-stone-50"><img src={image.image} alt={image.alt||""} className="aspect-[4/3] w-full object-cover"/><div className="flex items-center justify-between gap-3 p-3"><label className="cursor-pointer text-xs font-semibold text-navy-900">{uploading===`${title.startsWith("Imagens da hero")?"hero":"gallery"}-${index}`?"Enviando…":"Trocar"}<input type="file" accept="image/*" className="hidden" disabled={!!uploading} onChange={e=>{const file=e.target.files?.[0];if(file)onReplace(index,file);e.currentTarget.value=""}}/></label><button type="button" onClick={()=>onRemove(index)} className="text-xs font-semibold text-red-600">Remover</button></div>{renderMeta?.(image as GalleryImage,index)}</article>)}</div></div>}
