"use client";
import { useState,useEffect } from "react";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { Menu,X } from "lucide-react";
import { Logo } from "@/components/brand/Logo";
import { Button } from "@/components/ui/Button";
import { cn } from "@/lib/utils";
import { SITE } from "@/lib/site";
import { track } from "@/lib/analytics";
import { buildWhatsAppUrl as waUrl } from "@/lib/utils";
const nav=[{href:"/",label:"Início"},{href:"/#servicos",label:"Serviços"},{href:"/#galeria",label:"Galeria"},{href:"/quem-somos",label:"Quem somos"},{href:"/#contato",label:"Contato"}];
export function Header({initialLogo,initialWordmark}:{initialLogo?:string;initialWordmark?:string}){const[open,setOpen]=useState(false),[scrolled,setScrolled]=useState(false);const pathname=usePathname();useEffect(()=>{const onScroll=()=>setScrolled(window.scrollY>24);window.addEventListener("scroll",onScroll,{passive:true});return()=>window.removeEventListener("scroll",onScroll)},[]);useEffect(()=>setOpen(false),[pathname]);const handleWhatsApp=()=>track({name:"whatsapp_click",props:{location:"header"}});return <header className={cn("fixed inset-x-0 top-0 z-50 transition-all duration-500",scrolled?"bg-stone-50/92 backdrop-blur-xl border-b border-stone-200/80 shadow-sm":"bg-stone-50/75 backdrop-blur-sm")}><div className="mx-auto max-w-[1280px] px-4 sm:px-6 lg:px-8"><div className="flex h-[78px] md:h-[92px] items-center justify-between"><Logo size="lg" initialLogo={initialLogo} initialWordmark={initialWordmark}/><nav className="hidden md:flex items-center gap-8">{nav.map(item=><Link key={item.href} href={item.href} className="relative py-3 text-[13px] font-medium tracking-wide text-navy-800/80 hover:text-navy-900 transition-colors after:absolute after:inset-x-0 after:bottom-0 after:h-px after:origin-left after:scale-x-0 after:bg-navy-700 after:transition-transform hover:after:scale-x-100">{item.label}</Link>)}</nav><div className="hidden md:block"><a href={waUrl(SITE.whatsapp,"Olá, gostaria de solicitar um orçamento para uma reforma.")} target="_blank" rel="noopener noreferrer" onClick={handleWhatsApp}><Button variant="accent" size="sm">Solicitar orçamento</Button></a></div><button type="button" className="md:hidden p-2 rounded-lg text-navy-800" onClick={()=>setOpen(!open)} aria-label={open?"Fechar menu":"Abrir menu"} aria-expanded={open}>{open?<X size={24}/>:<Menu size={24}/>}</button></div></div>{open&&<div className="md:hidden border-t border-stone-200 bg-stone-50/98 backdrop-blur-xl"><nav className="flex flex-col px-4 py-5 gap-1">{nav.map(item=><Link key={item.href} href={item.href} className="px-3 py-3.5 text-base font-medium text-navy-800 rounded-lg hover:bg-stone-100">{item.label}</Link>)}<a href={waUrl(SITE.whatsapp,"Olá, gostaria de solicitar um orçamento para uma reforma.")} target="_blank" rel="noopener noreferrer" onClick={handleWhatsApp} className="mt-3"><Button variant="accent" className="w-full">Solicitar orçamento</Button></a></nav></div>}</header>}
