"use client";
import dynamic from "next/dynamic";
import { useState } from "react";
import { DEFAULT_HOMEPAGE,type HomepageContent,type GalleryImage } from "@/lib/cms-defaults";
import { createClient } from "@/lib/supabase/client";
const HeroBlock=dynamic(()=>import("./blocks/HeroBlock"),{ssr:false,loading:()=> <BlockLoading title="Hero"/>});
const CategoriesBlock=dynamic(()=>import("./blocks/CategoriesBlock"),{ssr:false,loading:()=> <BlockLoading title="Categorias"/>});
const GalleryBlock=dynamic(()=>import("./blocks/GalleryBlock"),{ssr:false,loading:()=> <BlockLoading title="Galeria"/>});
const MethodBlock=dynamic(()=>import("./blocks/MethodBlock"),{ssr:false,loading:()=> <BlockLoading title="Método"/>});
const CtaBlock=dynamic(()=>import("./blocks/CtaBlock"),{ssr:false,loading:()=> <BlockLoading title="CTA"/>});
function normalize(value:unknown):HomepageContent{const v=value&&typeof value==="object"?value as Partial<HomepageContent>:{};return {...DEFAULT_HOMEPAGE,...v,hero:{...DEFAULT_HOMEPAGE.hero,...(v.hero??{})},areas:{...DEFAULT_HOMEPAGE.areas,...(v.areas??{}),categories:Array.isArray(v.areas?.categories)?v.areas.categories:DEFAULT_HOMEPAGE.areas.categories},gallery:{...DEFAULT_HOMEPAGE.gallery,...(v.gallery??{}),images:Array.isArray(v.gallery?.images)?v.gallery.images:[]},portfolio:{...DEFAULT_HOMEPAGE.portfolio,...(v.portfolio??{})},method:{...DEFAULT_HOMEPAGE.method,...(v.method??{})},finalCta:{...DEFAULT_HOMEPAGE.finalCta,...(v.finalCta??{})}}}
export default function AdminConteudoClient({initialValue,initialError}:{initialValue:unknown;initialError:string|null}){const[content,setContent]=useState(()=>normalize(initialValue));const[saving,setSaving]=useState(false);const[message,setMessage]=useState(initialError||"");const[uploading,setUploading]=useState("");
async function save(next=content){setSaving(true);setMessage("");const s=createClient();const{error}=await s.from("site_content").upsert({key:"homepage",value:next,updated_at:new Date().toISOString()},{onConflict:"key"});setMessage(error?error.message:"Conteúdo salvo e publicado.");if(!error)setContent(next);setSaving(false)}
async function uploadImage(section:"hero"|"gallery",file:File,index?:number){const key=section+"-"+(index??"new");setUploading(key);const s=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=section+"/"+crypto.randomUUID()+"."+ext;const up=await s.storage.from("site-media").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMessage(up.error.message);setUploading("");return}const{data}=s.storage.from("site-media").getPublicUrl(path);const next=section==="hero"?{...content,hero:{...content.hero,images:index===undefined?[...content.hero.images,{image:data.publicUrl,alt:"Obra Nascimento Reformas"}]:content.hero.images.map((item,i)=>i===index?{...item,image:data.publicUrl}:item)}}:{...content,gallery:{...content.gallery,images:index===undefined?[...content.gallery.images,{image:data.publicUrl,alt:"Obra Nascimento Reformas",label:""}]:content.gallery.images.map((item,i)=>i===index?{...item,image:data.publicUrl}:item)}};await save(next);setUploading("")}
function removeImage(section:"hero"|"gallery",index:number){const next=section==="hero"?{...content,hero:{...content.hero,images:content.hero.images.filter((_,i)=>i!==index)}}:{...content,gallery:{...content.gallery,images:content.gallery.images.filter((_,i)=>i!==index)}};setContent(next)}
return <div className="min-h-screen bg-stone-100"><header className="sticky top-0 z-20 border-b border-stone-200 bg-white/95 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><a href="/admin/dashboard" className="text-xs uppercase tracking-widest text-stone-500">← Dashboard</a><h1 className="mt-1 text-xl font-semibold text-navy-950">Conteúdo do site</h1></div><button onClick={()=>void save()} disabled={saving} className="rounded-lg bg-navy-900 px-5 py-2.5 text-sm font-semibold text-white">{saving?"Salvando…":"Salvar alterações"}</button></div></header><main className="mx-auto max-w-7xl space-y-7 px-5 py-8">{message&&<div className="border border-stone-200 bg-white p-3 text-sm text-navy-900">{message}</div>}<HeroBlock content={content.hero} setContent={hero=>setContent(c=>({...c,hero}))} uploading={uploading} onUpload={(file,index)=>void uploadImage("hero",file,index)} onRemove={index=>removeImage("hero",index)}/><CategoriesBlock content={content.areas} setContent={areas=>setContent(c=>({...c,areas}))}/><GalleryBlock content={content.gallery} setContent={gallery=>setContent(c=>({...c,gallery}))} uploading={uploading} onUpload={(file,index)=>void uploadImage("gallery",file,index)} onRemove={index=>removeImage("gallery",index)}/><MethodBlock content={content.method} setContent={method=>setContent(c=>({...c,method}))}/><CtaBlock content={content.finalCta} setContent={finalCta=>setContent(c=>({...c,finalCta}))}/><button onClick={()=>void save()} disabled={saving} className="rounded-lg bg-navy-900 px-6 py-3 text-sm font-semibold text-white">{saving?"Salvando…":"Salvar e publicar tudo"}</button></main></div>}
function BlockLoading({title}:{title:string}){return <section className="min-h-40 animate-pulse border border-stone-200 bg-white p-7"><div className="h-6 w-40 rounded bg-stone-200"/><p className="mt-4 text-sm text-stone-400">Carregando editor {title}…</p></section>}
