"use client";
import Link from "next/link";
import { useEffect,useState,type ReactNode } from "react";
import { createClient } from "@/lib/supabase/client";
import { DEFAULT_HOMEPAGE,type HomepageContent,type ServiceCategory, type GalleryImage } from "@/lib/cms-defaults";

export default function AdminConteudoPage(){
 const [content,setContent]=useState<HomepageContent>(DEFAULT_HOMEPAGE);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");const [uploading,setUploading]=useState<string|null>(null);
 useEffect(()=>{(async()=>{const s=createClient();const {data,error}=await s.from("site_content").select("value").eq("key","homepage").maybeSingle();if(error)setMessage(`Erro ao carregar: ${error.message}`);else if(data?.value){const v=data.value as Partial<HomepageContent>;setContent({...DEFAULT_HOMEPAGE,...v,hero:{...DEFAULT_HOMEPAGE.hero,...(v.hero??{})},areas:{...DEFAULT_HOMEPAGE.areas,...(v.areas??{}),categories:Array.isArray(v.areas?.categories)?v.areas.categories:DEFAULT_HOMEPAGE.areas.categories},gallery:{...DEFAULT_HOMEPAGE.gallery,...(v.gallery??{}),images:Array.isArray(v.gallery?.images)?v.gallery.images:[]},method:{...DEFAULT_HOMEPAGE.method,...(v.method??{})},finalCta:{...DEFAULT_HOMEPAGE.finalCta,...(v.finalCta??{})}})}setLoading(false)})()},[]);
 async function persist(next:HomepageContent){const s=createClient();return s.from("site_content").upsert({key:"homepage",value:next,updated_at:new Date().toISOString()},{onConflict:"key"});}
 async function save(next=content){setSaving(true);setMessage("");const {error}=await persist(next);setMessage(error?`Não foi possível salvar: ${error.message}`:"Conteúdo salvo e publicado.");if(!error)setContent(next);setSaving(false)}
 async function uploadNew(file:File,kind:"hero"|"gallery"|`category-${number}`){setUploading(kind);setMessage("");const s=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const folder=kind==="hero"?"hero":kind==="gallery"?"gallery":"services";const path=`${folder}/${crypto.randomUUID()}.${ext}`;const up=await s.storage.from("site-media").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMessage(`Upload: ${up.error.message}`);setUploading(null);return}const {data}=s.storage.from("site-media").getPublicUrl(path);let next:HomepageContent;if(kind==="hero")next={...content,hero:{...content.hero,images:[...content.hero.images,{image:data.publicUrl,alt:"Obra Nascimento Reformas"}]}};else if(kind==="gallery")next={...content,gallery:{...content.gallery,images:[...content.gallery.images,{image:data.publicUrl,alt:"Obra Nascimento Reformas",label:""}]}};else{const index=Number(kind.split("-")[1]);next={...content,areas:{...content.areas,categories:content.areas.categories.map((item,i)=>i===index?{...item,image:data.publicUrl}:item)}}}const saved=await persist(next);setMessage(saved.error?`Imagem enviada, mas não salva: ${saved.error.message}`:"Imagem enviada e salva.");if(!saved.error)setContent(next);setUploading(null)}
 async function replaceImage(section:"hero"|"gallery",index:number,file:File){const key=`replace-${section}-${index}`;setUploading(key);setMessage("");const s=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const folder=section==="hero"?"hero":"gallery";const path=`${folder}/${crypto.randomUUID()}.${ext}`;const up=await s.storage.from("site-media").upload(path,file,{contentType:file.type,upsert:false});if(up.error){setMessage(`Upload: ${up.error.message}`);setUploading(null);return}const {data}=s.storage.from("site-media").getPublicUrl(path);const next=section==="hero"?{...content,hero:{...content.hero,images:content.hero.images.map((x,i)=>i===index?{...x,image:data.publicUrl}:x)}}:{...content,gallery:{...content.gallery,images:content.gallery.images.map((x,i)=>i===index?{...x,image:data.publicUrl}:x)}};const saved=await persist(next);setMessage(saved.error?`Nova imagem enviada, mas não salva: ${saved.error.message}`:"Imagem substituída, salva e publicada.");if(!saved.error)setContent(next);setUploading(null)}
 async function removeImage(section:"hero"|"gallery",index:number){const next=section==="hero"?{...content,hero:{...content.hero,images:content.hero.images.filter((_,i)=>i!==index)}}:{...content,gallery:{...content.gallery,images:content.gallery.images.filter((_,i)=>i!==index)}};setSaving(true);const r=await persist(next);setMessage(r.error?`Erro ao remover: ${r.error.message}`:"Imagem removida e salva.");if(!r.error)setContent(next);setSaving(false)}
 async function updateGalleryImage(index:number,changes:Partial<GalleryImage>){const next={...content,gallery:{...content.gallery,images:content.gallery.images.map((x,i)=>i===index?{...x,...changes}:x)}};setContent(next)}
 async function removeCategoryImage(index:number){const next={...content,areas:{...content.areas,categories:content.areas.categories.map((item,i)=>i===index?{...item,image:""}:item)}};await save(next)}
 function heroField(key:string,value:string){setContent(c=>({...c,hero:{...c.hero,[key]:value}} as HomepageContent))}
 function galleryField(key:string,value:string|number){setContent(c=>({...c,gallery:{...c.gallery,[key]:value}}))}
 function field(section:"areas"|"method"|"finalCta",key:string,value:string){setContent(c=>({...c,[section]:{...(c[section] as object),[key]:value}} as HomepageContent))}
 function categoryField(index:number,key:keyof ServiceCategory,value:string){setContent(c=>({...c,areas:{...c.areas,categories:c.areas.categories.map((item,i)=>i===index?{...item,[key]:value}:item)}}))}
 function addCategory(){setContent(c=>({...c,areas:{...c.areas,categories:[...c.areas.categories,{number:String(c.areas.categories.length+1).padStart(2,"0"),title:"Nova área de atuação",description:"Descreva aqui o serviço e o padrão de execução.",image:""}]}}))}
 function deleteCategory(index:number){if(!window.confirm("Excluir esta área de atuação?"))return;setContent(c=>({...c,areas:{...c.areas,categories:c.areas.categories.filter((_,i)=>i!==index).map((item,i)=>({...item,number:String(i+1).padStart(2,"0")}))}}))}
 if(loading)return <div className="min-h-screen bg-stone-100 p-8 text-stone-600">Carregando conteúdo…</div>;
 return <div className="min-h-screen bg-stone-100"><header className="sticky top-0 z-20 border-b border-stone-200 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><Link href="/admin/dashboard" className="text-xs uppercase tracking-widest text-stone-500">← Dashboard</Link><h1 className="mt-1 text-xl font-semibold text-navy-950">Editor do site</h1></div><button onClick={()=>save()} disabled={saving} className="rounded-lg bg-navy-900 px-5 py-2.5 text-sm font-semibold text-white disabled:opacity-50">{saving?"Salvando…":"Salvar alterações"}</button></div></header><main className="mx-auto max-w-7xl space-y-8 px-5 py-8">{message&&<div className="border border-stone-200 bg-white px-4 py-3 text-sm text-navy-900">{message}</div>}
 <EditorCard title="Hero · primeira impressão" subtitle="Texto, destaque, cores, degradê, grade e imagens são editáveis."><div className="grid gap-5 lg:grid-cols-2"><Input label="Eyebrow" value={content.hero.eyebrow} onChange={v=>heroField("eyebrow",v)}/><Input label="Título principal" value={content.hero.title} onChange={v=>heroField("title",v)}/><Input label="Texto que recebe destaque" value={content.hero.highlight} onChange={v=>heroField("highlight",v)}/><ColorInput label="Cor do destaque da hero" value={content.hero.accentColor} onChange={v=>heroField("accentColor",v)}/><TextArea label="Descrição" value={content.hero.description} onChange={v=>heroField("description",v)}/><Input label="Título do card" value={content.hero.panelTitle} onChange={v=>heroField("panelTitle",v)}/><TextArea label="Texto do card" value={content.hero.panelText} onChange={v=>heroField("panelText",v)}/><div className="grid grid-cols-2 gap-4"><Input label="Intervalo (ms)" type="number" value={String(content.hero.heroInterval)} onChange={v=>setContent(c=>({...c,hero:{...c.hero,heroInterval:Math.max(2500,Number(v)||6500)}}))}/><Input label="Degradê / overlay (%)" type="number" value={String(content.hero.heroOverlay)} onChange={v=>setContent(c=>({...c,hero:{...c.hero,heroOverlay:Math.min(90,Math.max(0,Number(v)||0))}}))}/></div></div><label className="mt-5 flex items-center gap-2 border-t border-stone-100 pt-5 text-sm font-medium text-navy-900"><input type="checkbox" checked={content.hero.showGrid} onChange={e=>setContent(c=>({...c,hero:{...c.hero,showGrid:e.target.checked}}))}/> Mostrar grade arquitetônica na hero</label><ImageManager title="Imagens da hero" images={content.hero.images} busy={uploading==="hero"} replacing={uploading} onUpload={f=>uploadNew(f,"hero")} onReplace={(i,f)=>replaceImage("hero",i,f)} onRemove={i=>removeImage("hero",i)}/></EditorCard>
 <EditorCard title="Áreas de atuação · cards" subtitle="Os cards da home são alimentados pelas categorias. Aqui você pode ajustar texto e capa; a troca de imagem é persistente."><div className="grid gap-5 lg:grid-cols-2"><Input label="Eyebrow" value={content.areas.eyebrow} onChange={v=>field("areas","eyebrow",v)}/><Input label="Título" value={content.areas.title} onChange={v=>field("areas","title",v)}/><Input label="Título em destaque" value={content.areas.highlight} onChange={v=>field("areas","highlight",v)}/><TextArea label="Descrição" value={content.areas.description} onChange={v=>field("areas","description",v)}/></div><div className="mt-8 grid gap-5 xl:grid-cols-2">{content.areas.categories.map((category,index)=><article key={`${category.id??"local"}-${index}`} className="overflow-hidden border border-stone-200 bg-stone-50"><div className="grid sm:grid-cols-[.9fr_1.1fr]"><div className="relative min-h-56 bg-stone-200">{category.image?<img src={category.image} alt={category.title} className="h-full min-h-56 w-full object-cover"/>:<div className="grid h-full min-h-56 place-items-center p-6 text-center text-sm text-stone-400">Sem imagem de capa</div>}<label className="absolute bottom-3 left-3 cursor-pointer rounded-md bg-white/95 px-3 py-2 text-xs font-semibold text-navy-900 shadow-sm">{uploading===`category-${index}`?"Enviando…":category.image?"Trocar capa":"Adicionar capa"}<input key={`${category.id??index}-${category.image}`} type="file" accept="image/*" className="hidden" disabled={!!uploading} onChange={e=>{const f=e.target.files?.[0];if(f)uploadNew(f,`category-${index}`);e.currentTarget.value=""}}/></label>{category.image&&<button type="button" onClick={()=>removeCategoryImage(index)} className="absolute right-3 top-3 rounded-md bg-black/70 px-2 py-1 text-xs text-white">Excluir imagem</button>}</div><div className="p-5"><div className="grid gap-4"><Input label="Número" value={category.number||""} onChange={v=>categoryField(index,"number",v)}/><Input label="Nome da área" value={category.title} onChange={v=>categoryField(index,"title",v)}/><TextArea label="Descrição curta" value={category.description} onChange={v=>categoryField(index,"description",v)}/></div><button type="button" onClick={()=>deleteCategory(index)} className="mt-5 text-xs font-semibold uppercase tracking-wider text-red-600">Excluir área</button></div></div></article>)}</div><button type="button" onClick={addCategory} className="mt-6 rounded-lg border border-navy-900 px-4 py-2.5 text-sm font-semibold text-navy-900">+ Adicionar área de atuação</button></EditorCard>
 <EditorCard title="Galeria horizontal" subtitle="As imagens rolam automaticamente para a esquerda. Não são clicáveis. No desktop, a imagem em evidência e a imagem sob o cursor ganham leve escala. Tudo é editável aqui."><div className="grid gap-5 lg:grid-cols-2"><Input label="Nome da seção" value={content.gallery.eyebrow} onChange={v=>galleryField("eyebrow",v)}/><Input label="Título da seção" value={content.gallery.title} onChange={v=>galleryField("title",v)}/><Input label="Intervalo automático (ms)" type="number" value={String(content.gallery.interval)} onChange={v=>galleryField("interval",Math.max(3500,Number(v)||6200))}/></div><ImageManager title="Imagens da galeria" images={content.gallery.images} busy={uploading==="gallery"} replacing={uploading} onUpload={f=>uploadNew(f,"gallery")} onReplace={(i,f)=>replaceImage("gallery",i,f)} onRemove={i=>removeImage("gallery",i)} renderMeta={(image,index)=><div className="grid gap-2 p-3"><Input label="Legenda" value={image.label||""} onChange={v=>updateGalleryImage(index,{label:v})}/><Input label="Texto alternativo" value={image.alt||""} onChange={v=>updateGalleryImage(index,{alt:v})}/></div>}/><p className="mt-4 text-xs text-stone-500">As alterações de legenda e texto alternativo entram no próximo “Salvar alterações”.</p></EditorCard>
 <EditorCard title="Método" subtitle="Seção de processo e confiança."><div className="grid gap-5 lg:grid-cols-2"><Input label="Eyebrow" value={content.method.eyebrow} onChange={v=>field("method","eyebrow",v)}/><Input label="Título" value={content.method.title} onChange={v=>field("method","title",v)}/><Input label="Destaque" value={content.method.highlight} onChange={v=>field("method","highlight",v)}/><TextArea label="Descrição" value={content.method.description} onChange={v=>field("method","description",v)}/></div></EditorCard>
 <EditorCard title="CTA final" subtitle="Última chamada para orçamento."><div className="grid gap-5 lg:grid-cols-3"><Input label="Título" value={content.finalCta.title} onChange={v=>field("finalCta","title",v)}/><Input label="Botão" value={content.finalCta.button} onChange={v=>field("finalCta","button",v)}/><TextArea label="Descrição" value={content.finalCta.description} onChange={v=>field("finalCta","description",v)}/></div></EditorCard>
 <button onClick={()=>save()} disabled={saving} className="rounded-lg bg-navy-900 px-6 py-3 text-sm font-semibold text-white disabled:opacity-50">{saving?"Salvando…":"Salvar e publicar tudo"}</button></main></div>
}
function EditorCard({title,subtitle,children}:{title:string;subtitle:string;children:ReactNode}){return <section className="border border-stone-200 bg-white p-6 shadow-sm sm:p-8"><div className="mb-7 border-b border-stone-100 pb-5"><h2 className="text-xl font-semibold text-navy-950">{title}</h2><p className="mt-1 text-sm text-stone-500">{subtitle}</p></div>{children}</section>}
function ImageManager({title,images,busy,replacing,onUpload,onReplace,onRemove,renderMeta}:{title:string;images:{image:string;alt?:string;label?:string}[];busy:boolean;replacing:string|null;onUpload:(file:File)=>void;onReplace:(index:number,file:File)=>void;onRemove:(index:number)=>void;renderMeta?:(image:{image:string;alt?:string;label?:string},index:number)=>ReactNode}){return <div className="mt-7 border-t border-stone-200 pt-7"><div className="flex items-center justify-between gap-4"><div><h3 className="font-semibold text-navy-900">{title}</h3><p className="text-sm text-stone-500">Adicione, substitua ou remova imagens diretamente pelo painel.</p></div><label className="cursor-pointer rounded-lg border border-navy-900 px-4 py-2 text-sm font-semibold text-navy-900">{busy?"Enviando…":"Adicionar imagem"}<input type="file" accept="image/*" className="hidden" disabled={busy} onChange={e=>{const f=e.target.files?.[0];if(f)onUpload(f);e.currentTarget.value=""}}/></label></div><div className="mt-5 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{images.map((image,index)=><div key={`${image.image}-${index}`} className="group relative overflow-hidden border border-stone-200 bg-stone-200"><img src={image.image} alt={image.alt||""} className="aspect-[4/3] w-full object-cover"/><div className="absolute left-2 top-2 flex gap-2 opacity-0 transition group-hover:opacity-100"><label className="cursor-pointer rounded bg-white/95 px-2 py-1 text-[11px] font-semibold text-navy-900 shadow">{replacing===`replace-gallery-${index}`||replacing===`replace-hero-${index}`?"Enviando…":"Trocar"}<input key={image.image} type="file" accept="image/*" className="hidden" disabled={!!replacing} onChange={e=>{const f=e.target.files?.[0];if(f)onReplace(index,f);e.currentTarget.value=""}}/></label><button type="button" onClick={()=>onRemove(index)} className="rounded bg-black/75 px-2 py-1 text-[11px] text-white">Remover</button></div>{renderMeta?renderMeta(image,index):<div className="p-2 text-xs text-stone-500">Imagem {String(index+1).padStart(2,"0")}</div>}</div>)}</div></div>}
function Input({label,value,onChange,type="text"}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-stone-500">{label}</span><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="h-11 w-full rounded-lg border border-stone-300 bg-white px-3 text-sm text-navy-900 outline-none focus:border-navy-700"/></label>}
function TextArea({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-stone-500">{label}</span><textarea value={value} onChange={e=>onChange(e.target.value)} rows={4} className="w-full rounded-lg border border-stone-300 bg-white p-3 text-sm text-navy-900 outline-none focus:border-navy-700"/></label>}
function ColorInput({label,value,onChange}:{label:string;value:string;onChange:(v:string)=>void}){return <label className="block"><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-stone-500">{label}</span><div className="flex gap-2"><input type="color" value={/^#[0-9A-Fa-f]{6}$/.test(value)?value:"#0B3A64"} onChange={e=>onChange(e.target.value.toUpperCase())} className="h-11 w-14 rounded border border-stone-300 bg-white p-1"/><input value={value} onChange={e=>onChange(e.target.value)} placeholder="#0B3A64" className="h-11 flex-1 rounded-lg border border-stone-300 bg-white px-3 font-mono text-sm text-navy-900 outline-none focus:border-navy-700"/></div></label>}
