"use client";

import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";

export default function ProjectGalleryPage({ params }: { params: Promise<{ id: string }> }) {
  const [id,setId]=useState<number|null>(null); const [project,setProject]=useState<any>(null); const [images,setImages]=useState<any[]>([]); const [uploading,setUploading]=useState(false); const [message,setMessage]=useState("");
  useEffect(()=>{params.then(p=>{const n=Number(p.id);setId(n);load(n)})},[]);
  async function load(projectId:number){const s=createClient();const [p,i]=await Promise.all([s.from("projects").select("id,title").eq("id",projectId).single(),s.from("project_images").select("*").eq("project_id",projectId).order("display_order")]);setProject(p.data);setImages(i.data??[])}
  async function upload(file:File){if(!id)return;setUploading(true);const s=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"jpg";const path=`projects/${id}/${crypto.randomUUID()}.${ext}`;const up=await s.storage.from("site-media").upload(path,file,{contentType:file.type});if(up.error){setMessage(up.error.message);setUploading(false);return}const {data}=s.storage.from("site-media").getPublicUrl(path);const ins=await s.from("project_images").insert({project_id:id,url:data.publicUrl,alt:project?.title,display_order:images.length});if(ins.error)setMessage(ins.error.message);else await load(id);setUploading(false)}
  async function remove(image:any){if(!id)return;const s=createClient();const {error}=await s.from("project_images").delete().eq("id",image.id);if(error)setMessage(error.message);else await load(id)}
  if(!id||!project)return <div className="min-h-screen bg-stone-100 p-8">Carregando galeria…</div>;
  return <div className="min-h-screen bg-stone-100"><header className="border-b border-stone-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><div><Link href="/admin/projetos" className="text-xs uppercase tracking-widest text-stone-500">← Portfólio</Link><h1 className="mt-1 text-xl font-semibold text-navy-950">Galeria · {project.title}</h1></div><Link href={`/portfolio/${project.slug||""}`} className="text-sm text-navy-700">Ver projeto ↗</Link></div></header><main className="mx-auto max-w-7xl px-5 py-8"><div className="flex items-center justify-between border border-stone-200 bg-white p-6"><div><h2 className="font-semibold text-navy-900">Imagens da obra</h2><p className="mt-1 text-sm text-stone-500">Adicione quantas imagens quiser. A ordem segue a sequência de envio.</p></div><label className="cursor-pointer rounded-lg bg-navy-900 px-4 py-2.5 text-sm font-semibold text-white">{uploading?"Enviando…":"Adicionar imagens"}<input type="file" multiple accept="image/*" className="hidden" disabled={uploading} onChange={async e=>{for(const f of Array.from(e.target.files??[]))await upload(f);e.currentTarget.value=""}}/></label></div>{message&&<p className="mt-4 border border-red-100 bg-red-50 p-3 text-sm text-red-700">{message}</p>}<div className="mt-6 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{images.map((image,index)=><figure key={image.id} className="group relative overflow-hidden border border-stone-200 bg-white"><img src={image.url} alt={image.alt||project.title} className="aspect-[4/3] w-full object-cover transition duration-500 group-hover:scale-[1.02]"/><figcaption className="flex items-center justify-between p-3 text-xs text-stone-500"><span>Imagem {String(index+1).padStart(2,"0")}</span><button onClick={()=>remove(image)} className="text-red-600">Excluir</button></figcaption></figure>)}{!images.length&&<div className="border border-dashed border-stone-300 p-12 text-center text-sm text-stone-500 sm:col-span-2 lg:col-span-3">Nenhuma imagem cadastrada ainda.</div>}</div></main></div>
}
