"use client";
import Link from "next/link";
import { useEffect, useState } from "react";
import { createClient } from "@/lib/supabase/client";
const keys=["site_name","whatsapp","region","accent_color","orange_color","seo_title","seo_description","logo_url","wordmark_url","favicon_url"];
const defaults={site_name:"Nascimento Reformas",whatsapp:"554892056761",region:"Palhoça e Grande Florianópolis - SC",accent_color:"#0B3A64",orange_color:"#E47C19",seo_title:"Nascimento Reformas | Reformas na Grande Florianópolis",seo_description:"Reformas residenciais e comerciais com precisão, planejamento e acabamento.",logo_url:"/logo.png",wordmark_url:"",favicon_url:"/logo.png"};
const isHex=(v:string)=>/^#[0-9A-Fa-f]{6}$/.test(v);
export default function AdminConfigPage(){const [values,setValues]=useState<Record<string,string>>(defaults);const [message,setMessage]=useState("");const [saving,setSaving]=useState(false);const [uploading,setUploading]=useState(false);const [uploadingWordmark,setUploadingWordmark]=useState(false);
useEffect(()=>{(async()=>{const s=createClient();const {data,error}=await s.from("settings").select("key,value").in("key",keys);if(error){setMessage(`Não foi possível carregar as configurações: ${error.message}`);return}for(const row of data??[])setValues(v=>({...v,[row.key]:row.value||defaults[row.key as keyof typeof defaults]||""}))})()},[]);
async function save(){setSaving(true);setMessage("");if(!isHex(values.accent_color)||!isHex(values.orange_color)){setMessage("As cores precisam estar no formato HEX, por exemplo #0B3A64.");setSaving(false);return}const s=createClient();for(const key of keys){const {error}=await s.from("settings").upsert({key,value:values[key]||"",updated_at:new Date().toISOString()},{onConflict:"key"});if(error){setMessage(`Erro ao salvar ${key}: ${error.message}`);setSaving(false);return}}setMessage("Configurações salvas e publicadas.");setSaving(false)}
async function upload(file:File,key:"logo_url"|"wordmark_url",setBusy:(v:boolean)=>void){setBusy(true);setMessage("");const s=createClient();const ext=file.name.split(".").pop()?.toLowerCase()||"png";const path=`brand/${key}/${crypto.randomUUID()}.${ext}`;const {error}=await s.storage.from("site-media").upload(path,file,{contentType:file.type,upsert:false});if(error){setMessage(`Upload: ${error.message}`);setBusy(false);return}const {data}=s.storage.from("site-media").getPublicUrl(path);const url=data.publicUrl;setValues(v=>({...v,[key]:url,...(key==="logo_url"?{favicon_url:url}:{})}));const writes=[s.from("settings").upsert({key,value:url,updated_at:new Date().toISOString()},{onConflict:"key"})];if(key==="logo_url")writes.push(s.from("settings").upsert({key:"favicon_url",value:url,updated_at:new Date().toISOString()}) as any);const results=await Promise.all(writes);const failed=results.find(r=>r.error);setMessage(failed?`Upload feito, mas não foi salvo: ${failed.error?.message}`:key==="logo_url"?"Logo e favicon atualizados.":"Segundo logo atualizado.");setBusy(false)}
return <div className="min-h-screen bg-stone-100"><header className="border-b border-stone-200 bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><div><Link href="/admin/dashboard" className="text-xs uppercase tracking-widest text-stone-500">← Dashboard</Link><h1 className="mt-1 text-xl font-semibold text-navy-950">Configurações</h1></div><button onClick={save} disabled={saving} className="rounded-lg bg-navy-900 px-5 py-2.5 text-sm font-semibold text-white">{saving?"Salvando…":"Salvar"}</button></div></header><main className="mx-auto max-w-5xl px-5 py-8">{message&&<div className="mb-6 border border-stone-200 bg-white p-3 text-sm text-navy-900">{message}</div>}
<section className="bg-white p-6 sm:p-8"><h2 className="text-xl font-semibold text-navy-950">Identidade da marca</h2><p className="mt-1 text-sm text-stone-500">Símbolo e segundo logo/wordmark são arquivos independentes.</p><div className="mt-6 grid gap-8 md:grid-cols-2"><BrandUpload title="Símbolo / logo principal" value={values.logo_url} busy={uploading} onUpload={f=>upload(f,"logo_url",setUploading)}/><BrandUpload title="Segundo logo · Nascimento Reformas" value={values.wordmark_url} busy={uploadingWordmark} onUpload={f=>upload(f,"wordmark_url",setUploadingWordmark)}/></div></section>
<section className="mt-7 bg-white p-6 sm:p-8"><h2 className="text-xl font-semibold text-navy-950">Identidade e cores</h2><div className="mt-6 grid gap-5 sm:grid-cols-2"><Input label="Nome do site" value={values.site_name} set={v=>setValues(x=>({...x,site_name:v}))}/><Input label="WhatsApp (somente números)" value={values.whatsapp} set={v=>setValues(x=>({...x,whatsapp:v.replace(/\D/g,"")}))}/><Input label="Região" value={values.region} set={v=>setValues(x=>({...x,region:v}))}/><ColorInput label="Azul oficial · destaque" value={values.accent_color} set={v=>setValues(x=>({...x,accent_color:v.toUpperCase()}))}/><ColorInput label="Laranja oficial · apoio" value={values.orange_color} set={v=>setValues(x=>({...x,orange_color:v.toUpperCase()}))}/></div><p className="mt-4 text-xs text-stone-500">Paleta oficial: azul #0B3A64 · laranja #E47C19. Os campos aceitam HEX para futuras edições.</p></section>
<section className="mt-7 bg-white p-6 sm:p-8"><h2 className="text-xl font-semibold text-navy-950">SEO</h2><div className="mt-6 grid gap-5"><Input label="Título SEO" value={values.seo_title} set={v=>setValues(x=>({...x,seo_title:v}))}/><label><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-stone-500">Descrição SEO</span><textarea rows={4} value={values.seo_description} onChange={e=>setValues(x=>({...x,seo_description:e.target.value}))} className="w-full rounded-lg border border-stone-300 p-3 text-sm"/></label></div></section><div className="py-8"><button onClick={save} disabled={saving} className="rounded-lg bg-navy-900 px-6 py-3 text-sm font-semibold text-white">{saving?"Salvando…":"Salvar configurações"}</button></div></main></div>}
function BrandUpload({title,value,busy,onUpload}:{title:string;value:string;busy:boolean;onUpload:(f:File)=>void}){return <div><p className="mb-3 text-sm font-semibold text-navy-900">{title}</p><div className="flex min-h-36 items-center justify-center border border-stone-200 bg-stone-50 p-5"><img src={value||"/logo.png"} alt={title} className="max-h-24 max-w-full object-contain"/></div><label className="mt-4 inline-flex cursor-pointer rounded-lg bg-navy-900 px-5 py-3 text-sm font-semibold text-white">{busy?"Enviando…":"Trocar arquivo"}<input type="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" className="hidden" disabled={busy} onChange={e=>e.target.files?.[0]&&onUpload(e.target.files[0])}/></label></div>}
function ColorInput({label,value,set}:{label:string;value:string;set:(v:string)=>void}){const safe=isHex(value)?value:"#000000";return <label><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-stone-500">{label}</span><div className="flex gap-3"><input type="color" value={safe} onChange={e=>set(e.target.value.toUpperCase())} className="h-11 w-14 cursor-pointer rounded border border-stone-300 p-1"/><input value={value} onChange={e=>set(e.target.value.toUpperCase())} className="h-11 flex-1 rounded-lg border border-stone-300 px-3 font-mono text-sm uppercase" placeholder="#0B3A64"/></div></label>}
function Input({label,value,set,type="text"}:{label:string;value:string;set:(v:string)=>void;type?:string}){return <label><span className="mb-2 block text-xs font-semibold uppercase tracking-wider text-stone-500">{label}</span><input type={type} value={value} onChange={e=>set(e.target.value)} className="h-11 w-full rounded-lg border border-stone-300 px-3 text-sm"/></label>}