import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { SITE } from "@/lib/site";
import { ProjectGallery } from "@/features/portfolio/ProjectGallery";

export default async function PortfolioDetail({ params }: { params: Promise<{ slug: string }> }) {
 const {slug}=await params;const supabase=await createClient();const [{data:project},{data:settings}]=await Promise.all([supabase.from("projects").select("*,categories(name),project_images(id,url,alt,display_order)").eq("slug",slug).eq("published",true).maybeSingle(),supabase.from("settings").select("key,value").eq("key","accent_color").maybeSingle()]);
 if(!project)notFound();const images=[...(project.project_images??[])].sort((a:any,b:any)=>(a.display_order??0)-(b.display_order??0));const accent=settings?.value||"#0B3A64";
 return <main className="min-h-screen bg-stone-50 text-navy-950"><header className="border-b border-stone-200 bg-white/92 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link href="/" className="text-sm font-semibold tracking-tight">Nascimento Reformas</Link><Link href="/#portfolio" className="text-sm text-stone-500 hover:text-navy-900">← Portfólio</Link></div></header><section className="mx-auto max-w-7xl px-5 pb-14 pt-16 sm:px-8 lg:px-12 lg:pt-24"><div className="max-w-5xl"><p className="text-xs font-semibold uppercase tracking-[.24em]" style={{color:accent}}>{project.categories?.name||"Projeto"} {project.year?`· ${project.year}`:""}</p><h1 className="mt-5 text-5xl font-semibold tracking-[-.055em] sm:text-7xl" style={{textShadow:`0 0 28px ${accent}18`}}>{project.title}</h1>{project.description&&<p className="mt-6 max-w-2xl text-lg leading-relaxed text-stone-600">{project.description}</p>}{project.location&&<p className="mt-5 text-xs font-semibold uppercase tracking-[.18em] text-stone-400">{project.location}</p>}</div></section><ProjectGallery projectTitle={project.title} cover={project.cover_image} images={images} accent={accent}/><section className="bg-[#0B3A64] px-5 py-20 text-white sm:px-8 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-white/55">Nascimento Reformas</p><h2 className="mt-3 text-3xl font-semibold">Tem uma obra parecida em mente?</h2></div><a href={`https://wa.me/${SITE.whatsapp}?text=${encodeURIComponent("Olá, gostaria de conversar sobre uma obra.")}`} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center border border-white/25 px-6 text-sm font-semibold hover:bg-white hover:text-navy-900">Solicitar orçamento ↗</a></div></section></main>;
}
