import Link from "next/link";
import { notFound } from "next/navigation";
import { createClient } from "@/lib/supabase/server";
import { SITE } from "@/lib/site";

export default async function PortfolioDetail({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params; const supabase = await createClient();
  const { data: project } = await supabase.from("projects").select("*, categories(name), project_images(id,url,alt,display_order)").eq("slug",slug).eq("published",true).maybeSingle();
  if (!project) notFound();
  const images = [...(project.project_images ?? [])].sort((a:any,b:any)=>a.display_order-b.display_order);
  const all = [project.cover_image ? {id:"cover",url:project.cover_image,alt:project.title} : null,...images].filter(Boolean) as any[];
  return <main className="min-h-screen bg-stone-50 text-navy-950"><header className="border-b border-stone-200 bg-white/90 backdrop-blur"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5"><Link href="/" className="text-sm font-semibold tracking-tight">Nascimento Reformas</Link><Link href="/#portfolio" className="text-sm text-stone-500 hover:text-navy-900">← Portfólio</Link></div></header><section className="mx-auto max-w-7xl px-5 pb-12 pt-16 sm:px-8 lg:px-12 lg:pt-24"><div className="max-w-4xl"><p className="text-xs font-semibold uppercase tracking-[.24em] text-navy-600">{project.categories?.name || "Projeto"} · {project.year || ""}</p><h1 className="mt-5 text-5xl font-semibold tracking-[-.05em] sm:text-7xl">{project.title}</h1><p className="mt-6 max-w-2xl text-lg leading-relaxed text-stone-600">{project.description}</p>{project.location&&<p className="mt-4 text-sm uppercase tracking-widest text-stone-400">{project.location}</p>}</div></section>{all.length>0?<section className="mx-auto max-w-[1400px] px-5 pb-24 sm:px-8 lg:px-12"><div className="grid gap-4 md:grid-cols-2">{all.map((image,index)=><figure key={image.id} className={`group relative overflow-hidden bg-stone-200 ${index===0?"md:col-span-2 md:aspect-[16/8]":"aspect-[4/3]"}`}><img src={image.url} alt={image.alt||project.title} className="h-full w-full object-cover transition duration-700 group-hover:scale-[1.025]"/><div className="absolute inset-x-0 bottom-0 h-24 bg-gradient-to-t from-black/40 to-transparent opacity-0 transition group-hover:opacity-100"/></figure>)}</div></section>:<section className="mx-auto max-w-7xl px-5 pb-24 text-stone-500">Nenhuma imagem adicional cadastrada.</section>}<section className="bg-navy-900 px-5 py-20 text-white sm:px-8 lg:px-12"><div className="mx-auto flex max-w-7xl flex-col gap-6 lg:flex-row lg:items-center lg:justify-between"><div><p className="text-xs uppercase tracking-[.22em] text-white/45">Nascimento Reformas</p><h2 className="mt-3 text-3xl font-semibold">Tem uma obra parecida em mente?</h2></div><a href={`https://wa.me/${SITE.whatsapp}?text=${encodeURIComponent("Olá, gostaria de conversar sobre uma obra.")}`} target="_blank" rel="noreferrer" className="inline-flex h-12 items-center justify-center border border-white/25 px-6 text-sm font-semibold hover:bg-white hover:text-navy-900">Solicitar orçamento ↗</a></div></section></main>
}
